INSERT INTO role(name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO role(name) VALUES ('ROLE_MANAGER') ON CONFLICT DO NOTHING;
INSERT INTO role(name) VALUES ('ROLE_RECRUIT_OFF') ON CONFLICT DO NOTHING;